name: flutter_blue
description:
  Flutter plugin for connecting and communicating with Bluetooth Low Energy devices,
  on Android and iOS
version: 0.7.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  convert: ^3.0.1
  protobuf: ^2.0.0
  rxdart: ^0.27.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  e2e: ^0.2.1
  flutter_driver:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.pauldemarco.flutter_blue
    pluginClass: FlutterBluePlugin
